development:
  adapter: postgresql
  encoding: unicode
  database: ifta_payments_development
  pool: 5
  username: bfischer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ifta_payments_test
  pool: 5
  username: myapp
  password: password1