# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9715dccee2324f0e2b4f2e2a08dfc58dc5249e2925589837759f6af359cc902a25ff1b935484bf6e15bd1c21467024083cf7c3616475893228a59253bd3631a0

test:
  secret_key_base: 009ab93f7d2e4c0fb9d10c593e60f6227af008beeff255c48e85dea2823235a5972e6ac290c73d963bd0df30fa4306334b7f027d33d1b725215a52d2557b82da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
